### ISSUE TITLE
🎉👍👋 What about maturity level?

### ISSUE THREAD

**Issue by piotr-yuxuan** [deercreeklabs/lancaster#1]
Thanks a lot for your prompt, detailed response to issue https://github.com/farbetter/roe/issues/1, and thank you very much for these libre projects you've been open sourcing to the community!

After roughly one year and ~260 commits this project seems to have reached some robustness 🙂 Would you mind to say if you consider it unstable? / do you use it on some pet project? / does it run somewhere in production? / how often does a new bug appear?

Cheers!

**Comment by chadharrington** [comment]
I use this library in several projects. None of them are currently running in production. The first production launch using this library will be in January 2019.

There are few if any users other than me at this point. Thus, the code paths that I use are known to work well. The tests cover the code fairly well, but bugs do show up from time to time as new use cases are explored. The library neeeds some good usage by multiple developers to be considered mature. To make that happen, I need to write some docs ;-)

The interface is fairly stable. I recently changed the top-level function names, which I had wanted to do for a while. I don't anticipate more changes to the API, other than adding new fns (like spec support). However, this should still be considered alpha or early beta code. Things may still change...

**Comment by chadharrington** [comment]
By the way, the Lancaster library has much better documentation now. Check it out and let me know if you have any questions.

**Comment by piotr-yuxuan** [comment]
>  much better documentation now

Indeed! Thanks a lot, that's great
