### ISSUE TITLE
Support for aliases

### ISSUE THREAD

**Issue by bartkl** [deercreeklabs/lancaster#16]
Hello,

Am I correct in noting that aliases are not supported?

https://avro.apache.org/docs/current/spec.html#Aliases

Thanks for the great work :),
Bart

**Comment by chadharrington** [comment]
Correct. There is the beginning of an implementation in Lancaster, but I never finished it. It could be added fairly easily. What is your use case?

**Comment by bartkl** [comment]
Avro is one of the output schema formats we wish to support for a schema generator we are writing. To be quite honest I'm not even entirely sure what we're going to use the aliases for or how important they are to us (I'm fairly new on the team).

I'm mostly trying to inventorize and explore the ecosystem of Clojure and the language itself. I really want to use it for our product, but it's hard to convince people ;).

Lancaster seems really nice, and I hope we'll end up using it. If we do, I'll get back to you about the aliases, or help implementing the feature.

Thanks so far.

**Comment by bartkl** [comment]
Hello Chad,

After some discussion, it seems we won't be needing the alias field. So unless you'd like to keep this issue open for your own administration/planning, it can be closed as far as I'm concerned.

Thanks!

**Comment by chadharrington** [comment]
Bart,
Thanks for the follow up and best wishes on your project. I will close this issue now.
